package edu.beihua.crm.mapper;

import edu.beihua.crm.model.ActivityRemark;
import jdk.dynalink.linker.LinkerServices;

import java.util.List;

public interface ActivityRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Thu May 04 16:15:44 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Thu May 04 16:15:44 CST 2023
     */
    int insert(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Thu May 04 16:15:44 CST 2023
     */
    int insertSelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Thu May 04 16:15:44 CST 2023
     */
    ActivityRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Thu May 04 16:15:44 CST 2023
     */
    int updateByPrimaryKeySelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Thu May 04 16:15:44 CST 2023
     */
    int updateByPrimaryKey(ActivityRemark record);

    //查询备注记录
    List<ActivityRemark> selectActivityRemarkForDetailByActivityId(String activityId);

    //添加备注记录
    int insertActivityRemark(ActivityRemark remark);

    //删除市场活动
    int deleltActivityRemark(String id);

    //修改试产备注活动
    int updateActivityRemark(ActivityRemark remark);
}