package edu.beihua.crm.mapper;

import edu.beihua.crm.model.ClueActivityRelation;

import java.util.List;

public interface ClueActivityRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Fri May 12 17:43:11 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Fri May 12 17:43:11 CST 2023
     */
    int insert(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Fri May 12 17:43:11 CST 2023
     */
    int insertSelective(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Fri May 12 17:43:11 CST 2023
     */
    ClueActivityRelation selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Fri May 12 17:43:11 CST 2023
     */
    int updateByPrimaryKeySelective(ClueActivityRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_activity_relation
     *
     * @mbggenerated Fri May 12 17:43:11 CST 2023
     */
    int updateByPrimaryKey(ClueActivityRelation record);

    //添加线索与市场的关系
    int insertActivtiyAndClue(List<ClueActivityRelation> clueActivityRelationList);

    //转换线索 使用clue_id查出该线索与市场活动的关系的所有关系
    List<ClueActivityRelation> selectActivtiyRelationClue(String clueId);

    //根据线索clueId 删除线索和市场活动的关系
    int deleteByClueId(String clueId);
}