package edu.beihua.crm.mapper;

import edu.beihua.crm.model.ClueRemark;

import java.util.List;

public interface ClueRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Tue May 09 19:22:08 CST 2023
     */
    int deleteByPrimaryKey(String id);

    int deleteByClueId(String clueId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Tue May 09 19:22:08 CST 2023
     */
    int insert(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Tue May 09 19:22:08 CST 2023
     */
    int insertSelective(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Tue May 09 19:22:08 CST 2023
     */
    ClueRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Tue May 09 19:22:08 CST 2023
     */
    int updateByPrimaryKeySelective(ClueRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue_remark
     *
     * @mbggenerated Tue May 09 19:22:08 CST 2023
     */
    int updateByPrimaryKey(ClueRemark record);

    //查询线索备注记录
    List<ClueRemark> selectClueRemarkForDetailByClueId(String clueId);

    //添加备注
    int insertClueRemark(ClueRemark clueRemark);

    //修改备注
    int updateClueById(ClueRemark clueRemark);

    //删除
    int deleltClueRemark(String id);

    //查询线索备注信息转存到客户备注表中一份
    List<ClueRemark> selectClueRemarkForDetailByClueIdToCustomRemark(String clueId);
}