package edu.beihua.crm.mapper;

import edu.beihua.crm.model.Clue;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sun May 07 20:50:55 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sun May 07 20:50:55 CST 2023
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sun May 07 20:50:55 CST 2023
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sun May 07 20:50:55 CST 2023
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sun May 07 20:50:55 CST 2023
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbggenerated Sun May 07 20:50:55 CST 2023
     */
    int updateByPrimaryKey(Clue record);

    //创建线索
    int insertClude(Clue clue);

    //条件分页查询
    List<Clue> selectAllClueByByConditionForPage(Map<String,Object> map);

    //查询总条数
    int selectCountOfClueByCondition(Map<String,Object> map);

    //更新线索
    int updateClue(Clue clue);

    //删除线索
    int deleteByIds(String[] ids);

    //根据id查询线索
    Clue selectClueDetailById(String clueId);

    //详细界面取消关联的市场活动
    int cancelClueRelationActivity(@Param("clueId") String clueId,@Param("activityId") String activityId);

    //更具线索id查询线索信息 用于转换
    Clue selectClueDetailByIdForConvert(String clueId);
}