package edu.beihua.crm.mapper;

import edu.beihua.crm.model.Activity;
import edu.beihua.crm.model.Customer;

import java.util.List;
import java.util.Map;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon May 15 10:21:23 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon May 15 10:21:23 CST 2023
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon May 15 10:21:23 CST 2023
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon May 15 10:21:23 CST 2023
     */
    Customer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon May 15 10:21:23 CST 2023
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_customer
     *
     * @mbggenerated Mon May 15 10:21:23 CST 2023
     */
    int updateByPrimaryKey(Customer record);

    int saveCustomer(Customer customer);

    //条件查询
    int selectAllCustomerCountByCondition(Map<String,Object> map);

    //条件计数查询
    List<Customer> selectCustomerByConditionForPage(Map<String,Object> map);

    //删除顾客
    int deleteByIds(String[] ids);

}