package edu.beihua.crm.ElementBank.mapper;

import edu.beihua.crm.ElementBank.model.Student;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed May 17 21:30:12 CST 2023
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Wed May 17 21:30:12 CST 2023
     */
    int insertSelective(Student record);
}